import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const emptyJob=()=>({id:crypto.randomUUID(),company:'',title:'',start:'',end:'',summary:''});
const emptySchool=()=>({id:crypto.randomUUID(),school:'',degree:'',subject:'',year:''});
function Field({label,value,onChange,type='text',options,disabled=false,...rest}) {return <label className="field"><span>{label}</span>{options?<select aria-label={label} value={value} disabled={disabled} required onChange={e=>onChange(e.target.value)} {...rest}><option value="">Choose…</option>{options.map(o=><option key={o}>{o}</option>)}</select>:<input aria-label={label} type={type} value={value} required disabled={disabled} onChange={e=>onChange(type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)} {...rest}/>}</label>;}
function App(){
 const runId=new URLSearchParams(location.search).get('run');
 const [variant,setVariant]=useState('standard'),[step,setStep]=useState(0),[error,setError]=useState(''),[receipt,setReceipt]=useState(''),[busy,setBusy]=useState(false);
 const [personal,setPersonal]=useState({name:'',email:'',phone:'',country:'',city:'',address:'',postal:''});
 const [preferences,setPreferences]=useState({role:'',mode:'',salary:'',startDate:'',sponsorship:'',visa:''});
 const [experience,setExperience]=useState([emptyJob()]),[education,setEducation]=useState([emptySchool()]);
 const [skills,setSkills]=useState([{name:'',level:''},{name:'',level:''}]),[consent,setConsent]=useState(false),[file,setFile]=useState(null);
 const [cityOptions,setCityOptions]=useState([]),[citiesLoading,setCitiesLoading]=useState(false),[emailStatus,setEmailStatus]=useState(''),[roleOpen,setRoleOpen]=useState(false);
 const form=useRef(),dialog=useRef();
 useEffect(()=>{if(runId)fetch(`/api/session/${runId}`).then(r=>{if(!r.ok)throw Error('Session not found');return r.json()}).then(s=>setVariant(s.variant)).catch(e=>setError(e.message));},[runId]);
 useEffect(()=>{let active=true;setCityOptions([]);if(!personal.country)return;setCitiesLoading(true);fetch(`/api/cities?country=${encodeURIComponent(personal.country)}`).then(r=>r.json()).then(v=>{if(active){setCityOptions(v);setCitiesLoading(false)}});return()=>{active=false}},[personal.country]);
 useEffect(()=>{let active=true;if(!personal.email){setEmailStatus('');return;}setEmailStatus('Checking email…');const t=setTimeout(()=>fetch(`/api/email?value=${encodeURIComponent(personal.email)}`).then(r=>r.json()).then(v=>{if(active)setEmailStatus(v.available?'Email available':'Email unavailable or invalid')}),250);return()=>{active=false;clearTimeout(t)}},[personal.email]);
 const p=(key,value)=>setPersonal(old=>({...old,[key]:value,...(key==='country'?{city:''}:{})}));
 const pref=(key,value)=>setPreferences(old=>({...old,[key]:value}));
 const update=(setter,id,key,value)=>setter(rows=>rows.map(r=>r.id===id?{...r,[key]:value}:r));
 function next(e){e.preventDefault();setError('');if(step===0&&emailStatus!=='Email available'){setError('Wait for a valid, available email.');return;}if(step===1&&!preferences.role){setError('Choose a target role.');return;}if(step===2&&experience.some(r=>r.end<r.start)){setError('Work end dates must be after start dates.');return;}if(step===3&&(!file||file.type!=='application/pdf'||file.size>2097152)){setError('Attach a PDF smaller than 2 MB.');return;}setStep(s=>s+1);}
 const payload=()=>({personal,preferences:{...preferences,...(preferences.sponsorship==='No'?{visa:''}:{})},experience:experience.map(({id,...r})=>r),education:education.map(({id,...r})=>r),skills,consent});
 async function submit(){setBusy(true);setError('');try{const body=new FormData();body.append('payload',JSON.stringify(payload()));body.append('resume',file);const r=await fetch(`/api/submit/${runId}`,{method:'POST',body});const result=await r.json();if(!r.ok)throw Error(result.error||'Submission failed');setReceipt(result.receipt);dialog.current.close();}catch(e){setError(e.message);dialog.current.close();}finally{setBusy(false)}}
 if(!runId)return <main><h1>Northstar Careers</h1><p>Open the application session link supplied with your task.</p></main>;
 return <div className={variant}><header><a href="#main">Northstar <strong>Careers</strong></a><span>Engineering · Application portal</span></header><div className="shell"><aside><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>Build what<br/>comes next.</h1><p>Tell us about your experience and the work you want to do.</p><ol>{['Contact','Preferences','Experience','Skills & résumé','Review'].map((label,i)=><li key={label} aria-current={step===i?'step':undefined}>{label}{i<step?' ✓':''}</li>)}</ol><details><summary>Application guidance</summary><p>All shown fields are required. Use the supplied application details and synthetic PDF. You can go back to edit before submitting.</p></details></aside><main id="main"><div className="step">STEP {step+1} OF 5</div>{receipt?<section role="status"><h2>Application received</h2><p>Receipt: {receipt}</p></section>:<><form ref={form} onSubmit={next}>
 {step===0&&<section><h2>Contact details</h2><div className="grid"><Field label="Full name" value={personal.name} onChange={v=>p('name',v)}/><Field label="Email" type="email" value={personal.email} onChange={v=>p('email',v)}/><p className="hint" role="status">{emailStatus}</p><Field label="Phone" type="tel" value={personal.phone} onChange={v=>p('phone',v)}/><Field label="Country" options={['Canada','United Kingdom']} value={personal.country} onChange={v=>p('country',v)}/><Field label="City" options={cityOptions} disabled={!personal.country||citiesLoading} value={personal.city} onChange={v=>p('city',v)}/>{citiesLoading&&<p role="status">Loading cities…</p>}<Field label="Street address" value={personal.address} onChange={v=>p('address',v)}/><Field label="Postal code" value={personal.postal} onChange={v=>p('postal',v)}/></div></section>}
 {step===1&&<section><h2>Work preferences</h2><div className="field"><span id="role-label">Target role</span><button type="button" aria-labelledby="role-label role-value" aria-haspopup="listbox" aria-expanded={roleOpen} onClick={()=>setRoleOpen(!roleOpen)} onKeyDown={e=>{if(e.key==='Escape')setRoleOpen(false)}}><span id="role-value">{preferences.role||'Choose role…'}</span></button>{roleOpen&&<div role="listbox" aria-label="Target role options">{['Frontend Engineer','Full Stack Engineer','Platform Engineer'].map(role=><button type="button" role="option" aria-selected={preferences.role===role} key={role} onClick={()=>{pref('role',role);setRoleOpen(false)}}>{role}</button>)}</div>}</div><fieldset><legend>Work arrangement</legend>{['Remote','Hybrid','On-site'].map(mode=><label className="choice" key={mode}><input type="radio" required name="mode" checked={preferences.mode===mode} onChange={()=>pref('mode',mode)}/>{mode}</label>)}</fieldset><div className="grid"><Field label="Expected annual salary" type="number" min="1" value={preferences.salary} onChange={v=>pref('salary',v)}/><Field label="Available start date" type="date" value={preferences.startDate} onChange={v=>pref('startDate',v)}/><Field label="Require sponsorship" options={['Yes','No']} value={preferences.sponsorship} onChange={v=>pref('sponsorship',v)}/>{preferences.sponsorship==='Yes'&&<Field label="Visa category" options={['Work permit','Skilled worker','Other']} value={preferences.visa} onChange={v=>pref('visa',v)}/>}</div></section>}
 {step===2&&<section><h2>Experience & education</h2>{experience.map((r,i)=><fieldset key={r.id}><legend>Work experience {i+1}</legend><div className="grid">{[['company','Company'],['title','Job title'],['start','Start date','date'],['end','End date','date'],['summary','Responsibilities']].map(([key,label,type])=><Field key={key} label={label} type={type} value={r[key]} onChange={v=>update(setExperience,r.id,key,v)}/>)}</div>{experience.length>1&&<button type="button" onClick={()=>setExperience(rows=>rows.filter(row=>row.id!==r.id))}>Remove work experience {i+1}</button>}</fieldset>)}<button type="button" onClick={()=>setExperience(rows=>[...rows,emptyJob()])}>Add work experience</button>{education.map((r,i)=><fieldset key={r.id}><legend>Education {i+1}</legend><div className="grid"><Field label="School" value={r.school} onChange={v=>update(setEducation,r.id,'school',v)}/><Field label="Degree" options={['Bachelor','Master','Doctorate']} value={r.degree} onChange={v=>update(setEducation,r.id,'degree',v)}/><Field label="Subject" value={r.subject} onChange={v=>update(setEducation,r.id,'subject',v)}/><Field label="Graduation year" type="number" min="1950" max="2035" value={r.year} onChange={v=>update(setEducation,r.id,'year',v)}/></div>{education.length>1&&<button type="button" onClick={()=>setEducation(rows=>rows.filter(row=>row.id!==r.id))}>Remove education {i+1}</button>}</fieldset>)}<button type="button" onClick={()=>setEducation(rows=>[...rows,emptySchool()])}>Add education</button></section>}
 {step===3&&<section><h2>Skills & résumé</h2><table><caption>Core skills</caption><thead><tr><th>Skill</th><th>Proficiency</th></tr></thead><tbody>{skills.map((r,i)=><tr key={i}><td><Field label={`Skill ${i+1}`} value={r.name} onChange={v=>setSkills(rows=>rows.map((row,j)=>j===i?{...row,name:v}:row))}/></td><td><Field label={`Proficiency ${i+1}`} options={['Beginner','Intermediate','Advanced']} value={r.level} onChange={v=>setSkills(rows=>rows.map((row,j)=>j===i?{...row,level:v}:row))}/></td></tr>)}</tbody></table><label className="field upload"><span>Résumé PDF</span><input aria-label="Résumé PDF" type="file" accept="application/pdf,.pdf" required={!file} onChange={e=>setFile(e.target.files[0]||null)}/><small>{file?`Attached: ${file.name} (${file.size} bytes)`:'PDF only · Up to 2 MB'}</small></label><label className="choice"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>I consent to processing this application</label></section>}
 {step===4&&<section><h2>Review your application</h2><p>Check your details before the final confirmation.</p>{Object.entries(payload()).map(([group,value])=><details open key={group}><summary>{group}</summary><pre>{JSON.stringify(value,null,2)}</pre></details>)}<p>Résumé: {file?.name}</p></section>}
 <div className="actions">{step>0&&<button type="button" onClick={()=>{setStep(s=>s-1);setError('')}}>Back</button>}{step<4?<button className="primary" type="submit">Continue</button>:<button className="primary" type="button" onClick={()=>dialog.current.showModal()}>Submit application</button>}</div></form>{error&&<p role="alert" className="error">{error}</p>}<dialog ref={dialog} aria-labelledby="confirm-title"><h2 id="confirm-title">Confirm application</h2><p>Submit these details and your attached résumé?</p><div className="actions"><button disabled={busy} onClick={()=>dialog.current.close()}>Keep editing</button><button className="primary" disabled={busy} onClick={submit}>{busy?'Submitting…':'Confirm and submit'}</button></div></dialog></>}</main></div><footer>Northstar · Synthetic application research environment</footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
